trigger: 
 - main
 
pr: none

pool:
  name: TestAg


resources:
  pipelines:
  - pipeline: build-pipeline
    source: Build-CI
    trigger: true
      


variables:
  buildConfiguration: 'Release'

steps:
- script: echo 'DEPLOY!!'
  displayName: 'TEST'
